### PR TITLE
fix warning in endian.h

### LINKED ISSUE #140: warnings from cdt provided `endian.h`
Using some functions within cdt provided `endian.h` causes compile warnings,
```
In file included from /home/runner/work/eos-evm/eos-evm/contract/src/../../silkworm/core/silkworm/common/util.hpp:24:
/usr/opt/cdt/3.1.0/bin/../include/libc/endian.h:32:25: warning: '&' within '|' [-Wbitwise-op-parentheses]
        return __x>>24 | __x>>8&0xff00 | __x<<8&0xff0000 | __x<<24;
                       ~ ~~~~~~^~~~~~~
/usr/opt/cdt/3.1.0/bin/../include/libc/endian.h:32:25: note: place parentheses around the '&' expression to silence this warning
        return __x>>24 | __x>>8&0xff00 | __x<<8&0xff0000 | __x<<24;
                               ^
                         (            )
/usr/opt/cdt/3.1.0/bin/../include/libc/endian.h:32:41: warning: '&' within '|' [-Wbitwise-op-parentheses]
        return __x>>24 | __x>>8&0xff00 | __x<<8&0xff0000 | __x<<24;
                                       ~ ~~~~~~^~~~~~~~~
/usr/opt/cdt/3.1.0/bin/../include/libc/endian.h:32:41: note: place parentheses around the '&' expression to silence this warning
        return __x>>24 | __x>>8&0xff00 | __x<<8&0xff0000 | __x<<24;
                                               ^
                                         (              )
/usr/opt/cdt/3.1.0/bin/../include/libc/endian.h:37:23: warning: operator '<<' has lower precedence than '+'; '+' will be evaluated first [-Wshift-op-parentheses]
        return __bswap32(__x)+0ULL<<32 | __bswap32(__x>>32);
               ~~~~~~~~~~~~~~^~~~~~~
/usr/opt/cdt/3.1.0/bin/../include/libc/endian.h:37:23: note: place parentheses around the '+' expression to silence this warning
        return __bswap32(__x)+0ULL<<32 | __bswap32(__x>>32);
                             ^
               (                  )
3 warnings generated.
```

### PR DESCRIPTION
**Pull request by dimas1185**
fixes #140 

## API Changes
- [ ] API Changes

## Documentation Additions
- [ ] Documentation Additions

### CODE REVIEW

**Review by larryk85 — APPROVED** [review]

**Review by spoonincode — CHANGES_REQUESTED** [review]
that doesn't fix the warning
https://github.com/eosnetworkfoundation/eos-evm/actions/runs/4878774094/jobs/8704718768#step:6:71

**Comment by larryk85** [comment]
@dimas1185 please also make another PR for this to main as this will be a patch for RC.  Please look at https://github.com/eosnetworkfoundation/engineering/tree/main/process/versioning for reference.

**Comment by dimas1185** [comment]
@spoonincode should be good now

**Comment by dimas1185** [comment]
@larryk85 ubuntu 18 seems to fail on `release/4.0`. can we tackle it separately and force merge this one?

**Review by spoonincode — APPROVED** [review]

**Comment by ericpassmore** [comment]
Note:start
group: CLEANCODE
category: INTERNALS
summary: Resolve endian warnings.
Note: end

**Pull request merged**
