### PR TITLE
Remove antler run

### PR DESCRIPTION
**Pull request by dimas1185**
this partial resolution of #206 

Current state of Antler run in main branch is just empty binary. Most up to date work on Antler run can be found in https://github.com/AntelopeIO/cdt/tree/antler-run branch. On this point we are stopping any further development of Antler run and removing all its parts from `main` branch.

## API Changes
- [ ] API Changes

## Documentation Additions
- [ ] Documentation Additions

### CODE REVIEW

**Comment by ericpassmore** [comment]
Do we need to update the top level `CMakeLists.txt`?

https://github.com/AntelopeIO/cdt/blob/f897dc7b82c4de2b24f6baf6737a3339cab9bbb6/CMakeLists.txt#L96-L106

**Comment by ericpassmore** [comment]
Should we update `modules/InstallCDT.cmake`

https://github.com/AntelopeIO/cdt/blob/f897dc7b82c4de2b24f6baf6737a3339cab9bbb6/modules/InstallCDT.cmake#L77

**Comment by ericpassmore** [comment]
Should we remove from `scripts/generate_tarball.sh`
https://github.com/AntelopeIO/cdt/blob/f897dc7b82c4de2b24f6baf6737a3339cab9bbb6/scripts/generate_tarball.sh#L77-L78

**Comment by dimas1185** [comment]
> Do we need to update the top level `CMakeLists.txt`?
> 
> https://github.com/AntelopeIO/cdt/blob/f897dc7b82c4de2b24f6baf6737a3339cab9bbb6/CMakeLists.txt#L96-L106

this PR is to remove `Antler RUN`. You are commenting `Antler PROJ` which is different part and I'll do this with a separate PR.

**Review by ericpassmore — APPROVED** [review]
LGTM

**Review by linh2931 — APPROVED** [review]

**Comment by ericpassmore** [comment]
Note:start
group: RELEASE
category: CHORE
summary: Remove unused antler run packed with CDT binaries.
Note:end

**Pull request merged**
