### PR TITLE
Add constexpr specifier to varints 

### LINKED ISSUE #13: Make varints compile-time constructible
The varints [unsigned_int](https://github.com/AntelopeIO/cdt/blob/3c5f7777383cef4581000a1f51603b7240ab65a1/libraries/eosiolib/core/eosio/varint.hpp#L22-L237) & [signed_int](https://github.com/AntelopeIO/cdt/blob/3c5f7777383cef4581000a1f51603b7240ab65a1/libraries/eosiolib/core/eosio/varint.hpp#L246-L464) are just serialization wrappers for type uint32_t & int32_t. They should be compile-time constructible to be available for compile time [constant expressions](https://en.cppreference.com/w/cpp/language/constant_expression).

### PR DESCRIPTION
**Pull request by smlu**
PR adds constexpr specifier to varint types.
Fix #13

### CODE REVIEW

**Comment by spoonincode** [comment]
It looks like your branch/fork was created before #4 went in. Unfortunately that's going to prevent CI from passing on this branch. If you can merge the latest of cdt's main in to your branch, that should get CI working again which would be nice.

This might be a simple enough change we can send through without CI working though.

**Comment by smlu** [comment]
Ah what a coincidence I should've checked other branches before making this PR. I'll update this branch to the latest main and hopefully get the the CI working.

**Comment by smlu** [comment]
It turns out that the [varint-cxpr](https://github.com/smlu/cdt/tree/varint-cxpr) branch is already up to date with the main branch (at the this time - [e5ec4c19](https://github.com/AntelopeIO/cdt/commit/e5ec4c19a59fa2ea389b960b8deddf1404b75912)). Is there any way to restart CI for this PR?

**Comment by spoonincode** [comment]
That's my mistake. #4 went in to the release branch and never was merged back to main :facepalm: sorry about that. I'll try to get that merged today and let you know

**Comment by spoonincode** [comment]
Okay, main has been updated. If you merge the latest with your branch it should clear it to run properly.

**Comment by smlu** [comment]
The [varint-cxpr](https://github.com/smlu/cdt/tree/varint-cxpr) branch is update to latest main, hopefully the CI will go through now.

**Comment by linh2931** [comment]
Close this in favor of https://github.com/AntelopeIO/cdt/pull/42. Thanks @smlu.

**Pull request closed without merging**
