### PR TITLE
fix capi crypto

### PR DESCRIPTION
**Pull request by NatPDeveloper**
## Change Description
- fix crypto capi by properly exposing through `internal_use_do_not_use` and `inline` functions
- fixes https://github.com/AntelopeIO/cdt/issues/17

## API Changes
- added crypto to capi

## Documentation Additions
- none

### CODE REVIEW

**Comment by spoonincode** [comment]
It looks like your branch/fork was created before #4 went in. Unfortunately that's going to prevent CI from passing on this branch. If you can merge the latest of cdt's main in to your branch, that should get CI working again.

If not, this might be a simple enough change we can review manually though.

**Comment by NatPDeveloper** [comment]
That should do it.

**Comment by arhag** [comment]
Sorry @NatPDeveloper I didn't realize pressing the update button would commit changes to the `main` branch of your fork. In the future, it would be best practice for you to use a branch other than `main` to create the PR for changes.

**Comment by NatPDeveloper** [comment]
It looks like the other PR handles this better, feel free to close.

**Comment by arhag** [comment]
Closing in favor of https://github.com/AntelopeIO/cdt/pull/21.

**Pull request closed without merging**
